### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by marc1uk** [jspricke/python-remind#16]
I'm getting the following trying to parse an ics file:
```
cat ~/mycal.ics | ics2rem
Traceback (most recent call last):
  File "/path/to/ics2rem", line 7, in <module>
    from remind import ics2rem
  File "/home/marc/.local/lib/python3.5/site-packages/remind.py", line 60
    self._reminders: dict[str, dict[str, Any]] = {}
                   ^
SyntaxError: invalid syntax
```
Is there a minimum python version? I'm running python 3.5.3

**Comment by jspricke** [comment]
>I'm getting the following trying to parse an ics file:
>```
>cat ~/mycal.ics | ics2rem
>Traceback (most recent call last):
>  File "/path/to/ics2rem", line 7, in <module>
>    from remind import ics2rem
>  File "/home/marc/.local/lib/python3.5/site-packages/remind.py", line 60
>    self._reminders: dict[str, dict[str, Any]] = {}
>                   ^
>SyntaxError: invalid syntax
>```
>Is there a minimum python version? I'm running python 3.5.3

The minimum Python version is currently 3.9, version 0.17.0 should work 
with Python 3.5, you can install it with:

pip install remind==0.17.0

Sorry for causing the issue, Python 3.9 is from 2020 and 3.5 from 2015, 
so I thought it was time to renovate.

Cheers Jochen

**Comment by marc1uk** [comment]
Thanks Jochen! It might be worth putting that on the requirements list. Not all linux distriubtions tend to keep their repositories up to date, and not all users update their OS on a regular basis. ;) 
Unfortunately with remind 0.17.0 i'm now getting a different syntax error:
```
Traceback (most recent call last):
  File "/path/to/ics2rem", line 7, in <module>
    from remind import ics2rem
  File "/home/marc/.local/lib/python3.5/site-packages/remind.py", line 62
    cmd = ['remind', f'-ppp{self._month}', '-b2', '-y', '-df',
                                        ^
SyntaxError: invalid syntax
```

**Comment by jspricke** [comment]
Ah true, 3.5 is even older, maybe v0.14.0 works but not sure. Which OS 
do you use that it has such old versions? Also, which version of Remind 
do you want to use with it?

**Comment by marc1uk** [comment]
I rolled back to 0.14, but it's now just hanging. It complained if ~/.reminders didn't exist (not sure if that's supposed to be a file or directory, i tried making both), but then just hangs indefinitely appearing to do nothing. :man_shrugging: 

I'm using Debian 9. Debian 10 was initially released July 2019, so I wouldn't call it especially ancient. I suppose that depends on whether you're the type to update to every new release as soon as you can. Personally I have little incentive to do so, though.

**Comment by jspricke** [comment]
* marc1uk ***@***.***> [2022-01-10 03:09]:
>I'm using Debian 9. Debian 10 was initially released July 2019, so I wouldn't call it especially ancient. I suppose that depends on whether you're the type to update to every new release as soon as you can. Personally I have little incentive to do so, though.

Debian 11 was released in 2021. Debian 9 has no security support since 
2020 and will loose long term support in June 2022:

https://wiki.debian.org/DebianReleases#Production_Releases

I don't intent to maintain software that is so old, sorry.

**Comment by marc1uk** [comment]
ok, no worries, maybe i'll try python-dateutil
