### ISSUE TITLE
Empty quotation sequence

### ISSUE THREAD

**Issue by walderich** [jspricke/python-remind#22]
I am trying to synchronize my reminders with a CalDAV server. After struggling with some issues of the official release 0.18.0, I installed the current master branch. Now I finally see all of my reminders in the calendar.

Now I have a special event, which is defined like this:
`MSG Sunrise [sunrise(trigdate())] - [sunset(trigdate())]%"%"`
Unfortunately this event is now added to each day of the calendar in the form `Sunrise 09:24 - 17:51%"%"`. But the documentation (i.e. `man remind`) states:

> If you use the sequence %"%" in a MSG or CAL-type reminder, then no calendar entry is produced for that reminder.

I guess events with this special sequence should be ignored, as the message is actually empty. Other events with non-empty quotations are parsed and displayed correctly.

**Comment by jspricke** [comment]
Thanks for pointing out, I have pushed a fix to master.
